# https://smashboards.com/threads/list-of-all-possible-character-states-ie-downdamage-downwait.400270/#post-19055623
# https://smashboards.com/threads/psa-animation-collaboration-needs-your-help.253384/
stateAnnotations = {
    "DeadDown": "Standard downward death",
    "DeadLeft": "Standard leftward death",
    "DeadRight": "Standard rightward death",
    "DeadUp": "Upward death used in 1P 'Team Kirby', etc.",
    "DeadUpStar": "Standard Star KO",
    "DeadUpStarIce": "Star KO while encased in ice (Freezie)",
    "DeadUpFall": "64-esque front fall, unused, I believe",
    "DeadUpFallHitCamera": "",
    "DeadUpFallHitCameraFlat": "",
    "DeadUpFallIce": "",
    "DeadUpFallHitCameraIce": "",
    "Sleep": "'Nothing' state, probably - it is the state Shiek/Zelda is in when their counterpart is the one currently playing",
    "Rebirth": "Entering on halo",
    "RebirthWait": "Waiting on halo",
    "Wait": "Standing state",
    "WalkSlow": "VERY slightly tilted forward. Character walks slowly.",
    "WalkMiddle": "Slightly tilted forward. Walks a little faster.",
    "WalkFast": "Tilted even more. Walks fast.",
    "Turn": "Tilt D-Stick in the other direction. Character turns around.",
    "TurnRun": "Tapping the other direction while running. Character swivels around.",
    "Dash": "A Dash",
    "Run": "After Dash, when character reaches their maximum velocity. Can no longer dashdance.",
    "RunDirect": "",
    "RunBrake": "Braking after running, D-Stick no longer held forward.",
    "KneeBend": "Pre-jump animation",
    "JumpF": "First jump forward",
    "JumpB": "First jump backward",
    "JumpAerialF": "Aerial jump forward",
    "JumpAerialB": "Aerial jump backward",
    "Fall": "Falling straight down",
    "FallF": "Falling with forward DI",
    "FallB": "Falling with backward DI",
    "FallAerial": "Falling after the second jump",
    "FallAerialF": "Falling after the second jump with forward DI",
    "FallAerialB": "Falling after the second jump with backward DI",
    "FallSpecial": "Special fall after UpB or airdodge",
    "FallSpecialF": "Special fall with forward DI",
    "FallSpecialB": "Special fall with backward DI",
    "DamageFall": "Tumbling",
    "Squat": "Going from stand to crouch",
    "SquatWait": "Crouching",
    "SquatRv": "Going from crouch to stand",
    "Landing": "Landing state, can be cancelled",
    "LandingFallSpecial": "Landing from special fall",
    "Attack11": "Standard attack 1",
    "Attack12": "Standard attack 2",
    "Attack13": "Standard attack 3",
    "Attack100Start": "Start of a looping standard attack",
    "Attack100Loop": "Middle of a looping standard attack",
    "Attack100End": "End of a looping standard attack",
    "AttackDash": "Dash attack",
    "AttackS3Hi": "High Ftilt",
    "AttackS3HiS": "High-mid Ftilt",
    "AttackS3S": "Mid Ftilt",
    "AttackS3LwS": "Low-mid Ftilt",
    "AttackS3Lw": "Low Ftilt",
    "AttackHi3": "Uptilt",
    "AttackLw3": "Downtilt",
    "AttackS4Hi": "High Fsmash",
    "AttackS4HiS": "High-mid Fsmash",
    "AttackS4S": "Mid Fsmash",
    "AttackS4LwS": "Low-mid Fsmash",
    "AttackS4Lw": "Low Fsmash",
    "AttackHi4": "Upsmash",
    "AttackLw4": "Downsmash",
    "AttackAirN": "Nair",
    "AttackAirF": "Fair",
    "AttackAirB": "Bair",
    "AttackAirHi": "Uair",
    "AttackAirLw": "Dair",
    "LandingAirN": "Landing during Nair",
    "LandingAirF": "Landing during Fair",
    "LandingAirB": "Landing during Bair",
    "LandingAirHi": "Landing during Uair",
    "LandingAirLw": "Landing during Dair",
    "DamageHi1": "Small flinch when getting hit in the head.",
    "DamageHi2": "Head knocked back a little when hit.",
    "DamageHi3": "Body reels backwards when hit.",
    "DamageN1": "Light hit in the torso.",
    "DamageN2": "Medium hit in the torso.",
    "DamageN3": "Heavy hit in the torso.",
    "DamageLw1": "Light hit at the feet, like a semi-trip.",
    "DamageLw2": "Medium hit at the feet.",
    "DamageLw3": "Heavy fit at the feet; often standing character hit the floor on all fours.",
    "DamageAir1": "Light hit while in the air.",
    "DamageAir2": "Medium hit while in the air.",
    "DamageAir3": "Heavy hit in the air; character reels backwards.",
    "DamageFlyHi": "",
    "DamageFlyN": "",
    "DamageFlyLw": "",
    "DamageFlyTop": "",
    "DamageFlyRoll": "",
    "LightGet": "Picking up an item",
    "HeavyGet": "Picking up a heavy item (barrel)",
    "LightThrowF": "Throwing items at standard speed",
    "LightThrowB": "",
    "LightThrowHi": "",
    "LightThrowLw": "",
    "LightThrowDash": "",
    "LightThrowDrop": "",
    "LightThrowAirF": "",
    "LightThrowAirB": "",
    "LightThrowAirHi": "",
    "LightThrowAirLw": "",
    "HeavyThrowF": "",
    "HeavyThrowB": "",
    "HeavyThrowHi": "",
    "HeavyThrowLw": "",
    "LightThrowF4": "Throwing items at Smash speed",
    "LightThrowB4": "",
    "LightThrowHi4": "",
    "LightThrowLw4": "",
    "LightThrowAirF4": "",
    "LightThrowAirB4": "",
    "LightThrowAirHi4": "",
    "LightThrowAirLw4": "",
    "HeavyThrowF4": "",
    "HeavyThrowB4": "",
    "HeavyThrowHi4": "",
    "HeavyThrowLw4": "",
    "Swing1": "Jab with battering item",
    "Swing3": "F-Tilt with battering item",
    "Swing4Start": "Starting animation to F-Smash with battering item",
    "Swing4": "F-Smash with battering item",
    "Swing42": "Second swing after F-Smash, only available to a few characters",
    "Swing4Hold": "Charging an F-Smash with the battering item",
    "SwingDash": "Dash attack with a battering item",
    "SwordSwing1": "Beam sword swings",
    "SwordSwing3": "",
    "SwordSwing4": "",
    "SwordSwingDash": "",
    "BatSwing1": "Home Run Bat swings",
    "BatSwing3": "",
    "BatSwing4": "",
    "BatSwingDash": "",
    "ParasolSwing1": "Parasol swings",
    "ParasolSwing3": "",
    "ParasolSwing4": "",
    "ParasolSwingDash": "",
    "HarisenSwing1": "Fan swings",
    "HarisenSwing3": "",
    "HarisenSwing4": "",
    "HarisenSwingDash": "",
    "StarRodSwing1": "Star Rod swings",
    "StarRodSwing3": "",
    "StarRodSwing4": "",
    "StarRodSwingDash": "",
    "LipStickSwing1": "Lip's Stick swings",
    "LipStickSwing3": "",
    "LipStickSwing4": "",
    "LipStickSwingDash": "",
    "ItemParasolOpen": "",
    "ItemParasolFall": "",
    "ItemParasolFallSpecial": "",
    "ItemParasolDamageFall": "",
    "LGunShoot": "Raygun shots",
    "LGunShootAir": "",
    "LGunShootEmpty": "",
    "LGunShootAirEmpty": "",
    "FireFlowerShoot": "",
    "FireFlowerShootAir": "",
    "ItemScrew": "",
    "ItemScrewAir": "",
    "DamageScrew": "",
    " DamageScrewAir": "",
    "ItemScopeStart": "",
    "ItemScopeRapid": "",
    "ItemScopeFire": "",
    "ItemScopeEnd": "",
    "ItemScopeAirStart": "",
    "ItemScopeAirRapid": "",
    "ItemScopeAirFire": "",
    "ItemScopeAirEnd": "",
    "ItemScopeStartEmpty": "",
    "ItemScopeRapidEmpty": "",
    "ItemScopeFireEmpty": "",
    "ItemScopeEndEmpty": "",
    "ItemScopeAirStartEmpty": "",
    "ItemScopeAirRapidEmpty": "",
    "ItemScopeAirFireEmpty": "",
    "ItemScopeAirEndEmpty": "",
    "LiftWait": "",
    "LiftWalk1": "",
    "LiftWalk2": "",
    "LiftTurn": "",
    "GuardOn": "Split-second startup lag when shielding.",
    "Guard": "Holding shield",
    "GuardOff": "Letting go off shield",
    "GuardSetOff": "Shield stun",
    "GuardReflect": "Beginning of shield, Powershield Window",
    "DownBoundU": "The 'failed to tech' bounce, facing up",
    "DownWaitU": "Laying on ground facing up",
    "DownDamageU": "Getting hit laying on ground facing up",
    "DownStandU": "Standing up when down, facing up.",
    "DownAttackU": "Get up attack from ground face up",
    "DownFowardU": "Rolling forward when down, facing up.",
    "DownBackU": "Rolling backwards when down, facing up.",
    "DownSpotU": "",
    "DownBoundD": "The 'failed to tech' bounce, facing down",
    "DownWaitD": "Laying on the ground face down",
    "DownDamageD": "Getting hit laying on the ground face down",
    "DownStandD": "Standing up when down, facing down",
    "DownAttackD": "Get up attack from ground face down",
    "DownFowardD": "Rolling forward when down, facing down",
    "DownBackD": "Rolling backwards when down, facing down",
    "DownSpotD": "",
    "Passive": "Neutral tech",
    "PassiveStandF": "Forward tech",
    "PassiveStandB": "Backward tech",
    "PassiveWall": "Wall tech",
    "PassiveWallJump": "Walljump tech/plain walljump",
    "PassiveCeil": "Ceiling tech",
    "ShieldBreakFly": "",
    "ShieldBreakFall": "",
    "ShieldBreakDownU": "",
    "ShieldBreakDownD": "",
    "ShieldBreakStandU": "",
    "ShieldBreakStandD": "",
    "FuraFura": "Shield-break tottering",
    "AirCatch": "Zair/Tether",
    "Catch": "Grab",
    "CatchPull": "Successfully grabbing a character - pulling them in",
    "CatchDash": "Dashgrab",
    "CatchDashPull": "",
    "CatchWait": "Grabbing and holding a character",
    "CatchAttack": "Pummel",
    "CatchCut": "When opponent breaks of a character's grab",
    "ThrowF": "Throw forward",
    "ThrowB": "Throw backwards",
    "ThrowHi": "Throw up.",
    "ThrowLw": "Throw down.",
    "CapturePulledHi": "Initial animation when grabbed by a tall character, i.e. when pulled in by Link or ZSS.",
    "CaptureWaitHi": "Held in grab by tall character.",
    "CaptureDamageHi": "Pummeled by tall character in grab.",
    "CapturePulledLw": "Grabbed by short character, i.e. Pikachu.",
    "CaptureWaitLw": "Held by short character.",
    "CaptureDamageLw": "Pummeled by short character in grab.",
    "CaptureCut": "Breaking away from a grab, staying on the ground.",
    "CaptureJump": "Breaking away from a grab, jumping backwards into the air.",
    "CaptureNeck": "",
    "CaptureFoot": "",
    "EscapeF": "Roll-dodge forwards.",
    "EscapeB": "Roll-dodge backwards.",
    "Escape": "",
    "EscapeAir": "Airdodge",
    "ReboundStop": "",
    "Rebound": "",
    "ThrownF": "",
    "ThrownB": "",
    "ThrownHi": "",
    "ThrownLw": "",
    "ThrownLwWomen": "",
    "Pass": "Drop through platform",
    "Ottotto": "Ledge teeter",
    "OttottoWait": "",
    "FlyReflectWall": "",
    "FlyReflectCeil": "",
    "StopWall": "",
    "StopCeil": "",
    "MissFoot": "",
    "CliffCatch": "Catching the ledge",
    "CliffWait": "Hanging on the ledge",
    "CliffClimbSlow": "Climbing the ledge, >100%",
    "CliffClimbQuick": "Climbing the ledge, <100%",
    "CliffAttackSlow": "Ledge attack, >100%",
    "liffAttackQuick": "Ledge attack, <100%",
    "CliffEscapeSlow": "Ledge roll, >100%",
    "CliffEscapeQuick": "Ledge roll, <100%",
    "CliffJumpSlow1": "",
    "CliffJumpSlow2": "",
    "CliffJumpQuick1": "",
    "CliffJumpQuick2": "",
    "AppealR": "Taunt right",
    "AppealL": "Taunt left",
    "ShoulderedWait": "",
    "ShoulderedWalkSlow": "",
    "ShoulderedWalkMiddle": "",
    "ShoulderedWalkFast": "",
    "ShoulderedTurn": "",
    "ThrownFF": "",
    "ThrownFB": "",
    "ThrownFHi": "",
    "ThrownFLw": "",
    "CaptureCaptain": "",
    "CaptureYoshi": "",
    "YoshiEgg": "",
    "CaptureKoopa": "",
    "CaptureDamageKoopa": "",
    "CaptureWaitKoopa": "",
    "ThrownKoopaF": "",
    "ThrownKoopaB": "",
    "CaptureKoopaAir": "",
    "CaptureDamageKoopaAir": "",
    "CaptureWaitKoopaAir": "",
    "ThrownKoopaAirF": "",
    "ThrownKoopaAirB": "",
    "CaptureKirby": "",
    "CaptureWaitKirby": "",
    "ThrownKirbyStar": "",
    "ThrownCopyStar": "",
    "ThrownKirby": "",
    "BarrelWait": "",
    "Bury": "",
    "BuryWait": "",
    "BuryJump": "",
    "DamageSong": "",
    "DamageSongWait": "",
    "DamageSongRv": "",
    "DamageBind": "",
    "CaptureMewtwo": "",
    "CaptureMewtwoAir": "",
    "ThrownMewtwo": "",
    "ThrownMewtwoAir": "",
    "WarpStarJump": "",
    "WarpStarFall": "",
    "HammerWait": "",
    "HammerWalk": "",
    "HammerTurn": "",
    "HammerKneeBend": "",
    "HammerFall": "",
    "HammerJump": "",
    "HammerLanding": "",
    "KinokoGiantStart": "Super/Poison mushroom states",
    "KinokoGiantStartAir": "",
    "KinokoGiantEnd": "",
    "KinokoGiantEndAir": "",
    "KinokoSmallStart": "",
    "KinokoSmallStartAir": "",
    "KinokoSmallEnd": "",
    "KinokoSmallEndAir": "",
    "Entry": "Warp in at beginning of match.",
    "EntryStart": "",
    "EntryEnd": "",
    "DamageIce": "",
    "DamageIceJump": "",
    "CaptureMasterhand": "",
    "CapturedamageMasterhand": "",
    "CapturewaitMasterhand": "",
    "ThrownMasterhand": "",
    "CaptureKirbyYoshi": "",
    "KirbyYoshiEgg": "",
    "CaptureLeadead": "",
    "CaptureLikelike": "",
    "DownReflect": "",
    "CaptureCrazyhand": "",
    "CapturedamageCrazyhand": "",
    "CapturewaitCrazyhand": "",
    "ThrownCrazyhand": "",
    "BarrelCannonWait": "",
    "Wait1": "Standing still on the ground, no button commands. The basic stance.",
    "Wait2": "A mini-taunt after a few seconds of standing still. Loops back to Wait1 once finished.",
    "Wait3": "Same as Wait2, different stance.",
    "Wait4": "Same as Wait2, different stance.",
    "WaitItem": "Standing still with an item in hand.",
    "SquatWait1": "",
    "SquatWait2": "An idle pose if you squat long enough, i.e. Mario looking around.",
    "SquatWaitItem": "Crouching while holding an item.",
    "GuardDamage": "",
    "EscapeN": "Sidestep.",
    "AttackS4Hold": "",
    "HeavyWalk1": "",
    "HeavyWalk2": "",
    "ItemHammerWait": "",
    "ItemHammerMove": "",
    "ItemBlind": "",
    "DamageElec": "Body shaking from an electrical attack.",
    "FuraSleepStart": "",
    "FuraSleepLoop": "",
    "FuraSleepEnd": "",
    "WallDamage": "",
    "CliffWait1": "",
    "CliffWait2": "",
    "SlipDown": "",
    "Slip": "",
    "SlipTurn": "",
    "SlipDash": "",
    "SlipWait": "",
    "SlipStand": "",
    "SlipAttack": "",
    "SlipEscapeF": "",
    "SlipEscapeB": "",
    "AppealS": "",
    "Zitabata": "",
    "CaptureKoopaHit": "",
    "ThrownKoopaEndF": "",
    "ThrownKoopaEndB": "",
    "CaptureKoopaAirHit": "",
    "ThrownKoopaAirEndF": "",
    "ThrownKoopaAirEndB": "",
    "ThrownKirbyDrinkSShot": "",
    "ThrownKirbySpitSShot": ""
}
